---
- name: Install hadoop
  hosts: all
  become: yes

  tasks:
  - name: Install hadoop
    yum: name=hadoop

  - name: Install hadoop hdfs
    yum: name=hadoop-hdfs

  - name: Install hadoop libhdfs
    yum: name=hadoop-libhdfs

  - name: Install YARN
    yum: name=hadoop-yarn

  - name: Install mapreduce
    yum: name=hadoop-mapreduce

  - name: Install hadoop client
    yum: name=hadoop-client

  - name: Install openssl
    yum: name=openssl
