---
- name: Install hadoop
  hosts: all

  tasks:
  - name: Install hadoop
    yum:
      name: hadoop
      state: present

  - name: Install hadoop hdfs
    yum:
      name: hadoop-hdfs
      state: present

  - name: Install hadoop libhdfs
    yum:
      name: hadoop-libhdfs
      state: present

  - name: Install YARN
    yum:
      name: hadoop-yarn
      state: present

  - name: Install mapreduce
    yum:
      name: hadoop-mapreduce
      state: present

  - name: Install hadoop client
    yum:
      name: hadoop-client
      state: present

  - name: Install openssl
    yum:
      name: openssl
      state: present
